{% set name = "conda-devenv" %}
{% set version = "1.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ESSS/{{ name }}/archive/{{version }}.tar.gz

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  entry_points:
    - conda-devenv = conda_devenv.devenv:main
  noarch_python: True

requirements:
  build:
    - python
    - setuptools
    - setuptools_scm
  run:
    - python
    - jinja2
    - pyyaml
    - six

test:
  requires:
    - pytest >=3
    - pytest-datadir >=1.0
    - pytest-mock
  imports:
    - conda_devenv
  commands:
    - conda-devenv --help
    - pytest tests
  source_files:
    - tests

about:
  home: https://github.com/ESSS/conda-devenv
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'A tool to work with multiple projects in develop-mode using conda-env.'
  doc_url: http://conda-devenv.readthedocs.io/
  dev_url: https://github.com/ESSS/conda-devenv

extra:
  recipe-maintainers:
    - edisongustavo
    - nicoddemus
    - gqmelo
    - tadeu
    - prusse-martin
